
import { Metadata } from 'next';
import OrderLayout from './orderLayout';

export const metadata: Metadata = {
   title: "Orders | RBS",
   description: "Generated by create next app",
};


export default OrderLayout

