import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeContextProvider } from "@/context/themeContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          {children}
        </ThemeContextProvider>
        <Toaster
          position="bottom-left"
          gutter={8}
          // containerStyle={{}}
          toastOptions={{
            // Define default options
            className: "shadow-md bg-white rounded-sm",
            duration: 3000,
            style: { borderRadius: '3px', },
          }}
        />
      </body>
    </html>
  );
}
